import turtle

bob = turtle.Turtle()
bob.speed(0)
bob.fillcolor("green")
bob.begin_fill()
bob.goto(-200,0)
bob.right(90)
bob.circle(180,180)
bob.goto(-200,0)
bob.end_fill()
bob.fillcolor("pink")
bob.begin_fill()
bob.penup()
bob.goto(-175,0)
bob.pendown()
bob.left(180)
bob.circle(150,180)
#bob.goto(-100,0)
bob.end_fill()
bob.penup()
bob.goto(0,-60)
bob.pendown()
bob.fillcolor("black")
bob.begin_fill()
bob.circle(5)
bob.end_fill()

bob.penup()
bob.goto(-100,-75)
bob.pendown()
bob.fillcolor("black")
bob.begin_fill()
bob.circle(5)
bob.end_fill()

bob.penup()
bob.goto(75,-75)
bob.pendown()
bob.fillcolor("black")
bob.begin_fill()
bob.circle(5)
bob.end_fill()
